name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node-version: ['10', '12', '']
        runs-on: [ubuntu-latest, macos-latest, windows-latest]

    name: Use Node.js ${{ matrix.node-version }} in ${{ matrix.runs-on }}

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@v2
    - run: |
        npm install
        npm test
      env:
        CI: true
